/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Lead } from "./types";

export const initialLeads: Lead[] = [
  {
    id: "lead_1",
    name: "Padaria e Confeitaria Bella Massa",
    niche: "Padaria e Confeitaria",
    location: "Moema, São Paulo",
    rating: 4.8,
    reviews: 1200,
    hasWebsite: false,
    hasGmbActive: true,
    hasPhone: true,
    phone: "(11) 99876-4321",
    leadScore: 98,
    status: "novo",
    captured: true,
    capturedAt: "2026-06-02T14:38:26Z",
    gmbAnalysis: "Empresa possui 4.8 estrelas no Google (1.200 avaliações) mas não tem site próprio ou presença estruturada em anúncios. Oportunidade de expansão digital é crítica.",
    avatarColor: "bg-surface-variant text-primary-container"
  },
  {
    id: "lead_2",
    name: "Studio Alpha Arquitetura",
    niche: "Arquitetura",
    location: "Vila Olímpia, SP",
    rating: 4.9,
    reviews: 42,
    hasWebsite: true,
    hasGmbActive: true,
    hasPhone: true,
    phone: "(11) 98765-1234",
    leadScore: 92,
    status: "interessado",
    captured: true,
    capturedAt: "2026-06-02T11:38:26Z",
    gmbAnalysis: "Arquitetos de luxo operando via Instagram. Site atual não é responsivo e não gera leads. Oportunidade de SEO Local e captação integrada de contatos.",
    avatarColor: "bg-blue-50 text-blue-800"
  },
  {
    id: "lead_3",
    name: "Clínica Sorriso Dental Care",
    niche: "Dentista",
    location: "Pinheiros, SP",
    rating: 4.7,
    reviews: 184,
    hasWebsite: false,
    hasGmbActive: true,
    hasPhone: true,
    phone: "(11) 97654-8899",
    leadScore: 89,
    status: "novo",
    captured: true,
    capturedAt: "2026-06-02T15:38:26Z",
    gmbAnalysis: "Clínica odontológica com excelente tráfego orgânico no Maps. Perda de 40% de conversão calculada por falta de sistema de agendamento online integrado.",
    avatarColor: "bg-teal-50 text-teal-800"
  },
  {
    id: "lead_4",
    name: "Padaria Delícias do Trigo",
    niche: "Padaria",
    location: "São Paulo, SP",
    rating: 4.4,
    reviews: 320,
    hasWebsite: false,
    hasGmbActive: true,
    hasPhone: true,
    phone: "(11) 99823-1122",
    leadScore: 95,
    status: "novo",
    captured: true,
    capturedAt: "2026-06-02T14:38:26Z",
    gmbAnalysis: "Famosa padaria local com alto volume de buscas no Maps, porém sem site para hospedar cardápio e receber pedidos diretos via WhatsApp (sem taxas de aplicativos).",
    avatarColor: "bg-surface-variant text-primary-container"
  },
  {
    id: "lead_5",
    name: "Mecânica Automotiva Silva",
    niche: "Oficina Mecânica",
    location: "Curitiba, PR",
    rating: 4.5,
    reviews: 80,
    hasWebsite: true,
    hasGmbActive: true,
    hasPhone: true,
    phone: "(41) 98877-6655",
    leadScore: 62,
    status: "interessado",
    captured: true,
    capturedAt: "2026-06-02T11:38:26Z",
    gmbAnalysis: "Perfil GMB ativo com avaliações recorrentes, mas o site atual possui falhas de responsividade móvel e não realiza captura estruturada de orçamentos e formulários.",
    avatarColor: "bg-blue-100 text-blue-800"
  },
  {
    id: "lead_6",
    name: "Clínica Odonto Clean",
    niche: "Dentista",
    location: "Rio de Janeiro, RJ",
    rating: 4.6,
    reviews: 210,
    hasWebsite: false,
    hasGmbActive: true,
    hasPhone: true,
    phone: "(21) 97722-3344",
    leadScore: 91,
    status: "negociacao",
    captured: true,
    capturedAt: "2026-06-01T16:38:26Z",
    gmbAnalysis: "Dentistas qualificados com fluxo constante de pacientes locais buscando no Maps, mas sem site próprio para apresentar especialidades ou avaliações de credibilidade.",
    avatarColor: "bg-amber-100 text-amber-800"
  },
  {
    id: "lead_7",
    name: "Restaurante Sabor Mineiro",
    niche: "Restaurante",
    location: "Belo Horizonte, MG",
    rating: 3.2,
    reviews: 45,
    hasWebsite: false,
    hasGmbActive: false,
    hasPhone: true,
    phone: "(31) 98833-4411",
    leadScore: 78,
    status: "fechado",
    captured: true,
    capturedAt: "2026-05-30T16:38:26Z",
    gmbAnalysis: "Empresa possui baixa avaliação e cadastro de GMB incompleto (não reivindicado). Não possui site. Perigo crítico à reputação digital da marca do restaurante.",
    avatarColor: "bg-slate-200 text-slate-700"
  },
  {
    id: "lead_8",
    name: "Bakery & Co.",
    niche: "Padaria",
    location: "São Paulo, SP",
    rating: 4.2,
    reviews: 145,
    hasWebsite: false,
    hasGmbActive: true,
    hasPhone: false,
    phone: "",
    leadScore: 84,
    status: "novo",
    captured: false,
    gmbAnalysis: "Sem site ou telefone oficiais cadastrados no Maps. Grande número de buscas locais sem canal direto de conversão ou engajamento.",
    avatarColor: "bg-surface-variant text-primary"
  },
  {
    id: "lead_9",
    name: "Tech Mechanics",
    niche: "Oficina Mecânica",
    location: "São Paulo, SP",
    rating: 4.8,
    reviews: 204,
    hasWebsite: true,
    hasGmbActive: true,
    hasPhone: true,
    phone: "(11) 97733-4455",
    leadScore: 45,
    status: "novo",
    captured: false,
    gmbAnalysis: "Possui site oficial ativo e ótima nota, mas as campanhas estão desordenadas e as mídias sociais não conectam ao fluxo. Potencial lead de remarketing.",
    avatarColor: "bg-surface-variant text-primary"
  },
  {
    id: "lead_10",
    name: "Limpeza Geral",
    niche: "Serviços Domésticos",
    location: "São Paulo, SP",
    rating: 4.1,
    reviews: 35,
    hasWebsite: true,
    hasGmbActive: true,
    hasPhone: true,
    phone: "(11) 96622-1100",
    leadScore: 50,
    status: "novo",
    captured: false,
    gmbAnalysis: "Possui site básico, porém com baixa pontuação de SEO e carregamento extremamente lento. Oportunidade de reformulação completa do funil de marketing.",
    avatarColor: "bg-surface-variant text-primary"
  },
  {
    id: "lead_11",
    name: "Pet Shop Amigo Fiel",
    niche: "Pet Shop",
    location: "Campinas, SP",
    rating: 5.0,
    reviews: 15,
    hasWebsite: false,
    hasGmbActive: true,
    hasPhone: true,
    phone: "(19) 97788-9900",
    leadScore: 62,
    status: "interessado",
    captured: false,
    gmbAnalysis: "Nota máxima perfeita (5.0) mas conta apenas com 15 avaliações locais no perfil. Ausência total de site para reservas e agendamentos de banho e tosa online.",
    avatarColor: "bg-surface-variant text-primary"
  }
];
